-- 코드를 입력하세요
SELECT b.USER_ID, b.NICKNAME
    , CONCAT(b.CITY,' ',b.STREET_ADDRESS1,' ',b.STREET_ADDRESS2) 전체주소
    , CONCAT(LEFT(b.TLNO,3),'-',SUBSTRING(b.TLNO, 4, 4),'-',RIGHT(b.TLNO,4)) 전화번호
FROM USED_GOODS_BOARD a
INNER JOIN USED_GOODS_USER b
ON a.WRITER_ID = b.USER_ID
GROUP BY 1
HAVING COUNT(b.USER_ID) >= 3
ORDER BY 1 DESC;