-- 코드를 입력하세요
SELECT a.APNT_NO, b.PT_NAME, b.PT_NO, c.MCDP_CD, c.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a
INNER JOIN PATIENT b ON a.PT_NO = b.PT_NO
INNER JOIN DOCTOR c ON a.MDDR_ID = c.DR_ID
WHERE a.APNT_CNCL_YN = 'N' AND a.MCDP_CD = 'CS' AND a.APNT_YMD LIKE '2022-04-13%'
ORDER BY 6;