-- 코드를 입력하세요
SELECT b.USER_ID, b.NICKNAME, SUM(a.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD a
INNER JOIN USED_GOODS_USER b
ON a.WRITER_ID = b.USER_ID
WHERE a.STATUS = 'DONE'
GROUP BY 1
HAVING TOTAL_SALES >= 700000
ORDER BY 3;