-- 코드를 입력하세요
SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN
(SELECT CAR_ID
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE MONTH(START_DATE) BETWEEN 8 AND 10
 GROUP BY 1
 HAVING COUNT(*) >= 5
)
AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY 1,2
ORDER BY 1, 2 DESC;
