-- 코드를 입력하세요
SELECT DISTINCT a.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR a
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b
ON a.CAR_ID = b.CAR_ID
WHERE a.CAR_TYPE = '세단' AND b.START_DATE LIKE '2022-10%'
ORDER BY 1 DESC;